name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
      
    - name: pwd
      run: pwd
    
    - name: ls
      run: ls -al
    
#     - name: tar
#       run: tar -cvzf artifact.tgz server client
      
#     - name: Archive production artifacts
#       uses: actions/upload-artifact@v1
#       with:
#           name: artifact.tgz
#           path: /home/runner/work/CFProxy/CFProxy/artifact.tgz
      
