name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
      
    - name: pwd
      run: pwd
    
    - name: ls
      run: ls /home/runner/work/RustScan/RustScan/target/debug -al
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
          name: rustscan
          path: /home/runner/work/RustScan/RustScan/target/debug/rustscan
      
